-- Assuming the table name is 'my_table' and the databases are 'QA' and 'UAT'

SELECT
    'QA' AS Source,
    QA.SYSTEM_NAME,
    QA.PROCESS_NAME,
    QA.OBJECT_NAME,
    QA.PARAMETER_NAME,
    QA.PARAMETER_VALUE,
    QA.ACTIVE_FLAG,
    QA.CREATED_BY,
    QA.UPDATED_BY,
    QA.UPDATED_TIMESTAMP,
    QA.STATUS_FLAG
FROM
    QA.my_table QA
FULL OUTER JOIN
    UAT.my_table UAT
ON
    QA.SYSTEM_NAME = UAT.SYSTEM_NAME
    AND QA.PROCESS_NAME = UAT.PROCESS_NAME
    AND QA.OBJECT_NAME = UAT.OBJECT_NAME
    AND QA.PARAMETER_NAME = UAT.PARAMETER_NAME
    AND QA.PARAMETER_VALUE = UAT.PARAMETER_VALUE
    AND QA.ACTIVE_FLAG = UAT.ACTIVE_FLAG
    AND QA.CREATED_BY = UAT.CREATED_BY
    AND QA.UPDATED_BY = UAT.UPDATED_BY
    AND QA.UPDATED_TIMESTAMP = UAT.UPDATED_TIMESTAMP
    AND QA.STATUS_FLAG = UAT.STATUS_FLAG
WHERE
    UAT.SYSTEM_NAME IS NULL -- Records in QA not in UAT

UNION ALL

SELECT
    'UAT' AS Source,
    UAT.SYSTEM_NAME,
    UAT.PROCESS_NAME,
    UAT.OBJECT_NAME,
    UAT.PARAMETER_NAME,
    UAT.PARAMETER_VALUE,
    UAT.ACTIVE_FLAG,
    UAT.CREATED_BY,
    UAT.UPDATED_BY,
    UAT.UPDATED_TIMESTAMP,
    UAT.STATUS_FLAG
FROM
    QA.my_table QA
FULL OUTER JOIN
    UAT.my_table UAT
ON
    QA.SYSTEM_NAME = UAT.SYSTEM_NAME
    AND QA.PROCESS_NAME = UAT.PROCESS_NAME
    AND QA.OBJECT_NAME = UAT.OBJECT_NAME
    AND QA.PARAMETER_NAME = UAT.PARAMETER_NAME
    AND QA.PARAMETER_VALUE = UAT.PARAMETER_VALUE
    AND QA.ACTIVE_FLAG = UAT.ACTIVE_FLAG
    AND QA.CREATED_BY = UAT.CREATED_BY
    AND QA.UPDATED_BY = UAT.UPDATED_BY
    AND QA.UPDATED_TIMESTAMP = UAT.UPDATED_TIMESTAMP
    AND QA.STATUS_FLAG = UAT.STATUS_FLAG
WHERE
    QA.SYSTEM_NAME IS NULL -- Records in UAT not in QA
